name: 'Build and deploy to Netlify'

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build WASM
        run: npm run build

      - name: Install dependencies web
        working-directory: ./web
        run: npm ci

      - name: Build app web
        working-directory: ./web
        run: npm run build

      # deploy the application to netlify
      - name: Publish
        uses: South-Paw/action-netlify-cli@1.0.1
        id: netlify
        with:
          # be sure to escape any double quotes with a backslash and note that the --json
          # flag has been passed when deploying - if you want the outputs to work you'll need to include it
          args: 'deploy --prod --dir \"./web/dist\" --message \"deploy [${{ github.sha }}]\"'
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
